spring:
  application:
    name: notification-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'


  grpc:
    server:
      enabled: false
    client:
      user-service:
        address: static://localhost:9093
        negotiationType: plaintext
        # Bağlantı yeniden deneme ekleyin
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        retry:
          enabled: true
          initialBackoff: 1000ms
          maxBackoff: 5000ms
          maxAttempts: 5

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true